In [30]:
import torch
import torch.nn as nn
from einops.layers.torch import Rearrange
from einops import repeat


In [12]:
p = nn.Parameter(torch.tensor([1.0]))
p

Parameter containing:
tensor([1.], requires_grad=True)

<img src='asset/softplus_function.png' />

In [17]:
x = torch.tensor([1.,1,1,1,1,1,1,1,1,1,1,1])
beta = 1.

def softplus(x):
    return torch.log(torch.exp(x)-1)

sp = softplus(x)
sp

tensor([0.5413, 0.5413, 0.5413, 0.5413, 0.5413, 0.5413, 0.5413, 0.5413, 0.5413,
        0.5413, 0.5413, 0.5413])

In [14]:
point_weight_init_value = torch.log(torch.exp(torch.full((12,), 1.)) - 1.)
point_weight_init_value

tensor([0.5413, 0.5413, 0.5413, 0.5413, 0.5413, 0.5413, 0.5413, 0.5413, 0.5413,
        0.5413, 0.5413, 0.5413])

In [15]:
torch.full((12,), 1.)

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [28]:
bij = nn.Linear(768, 12, bias=False)


pr = nn.Sequential(
                nn.Linear(768, 12),
                Rearrange('b ... h -> (b h) ...'))

pr

Sequential(
  (0): Linear(in_features=768, out_features=12, bias=True)
  (1): Rearrange('b ... h -> (b h) ...')
)

In [20]:
def exists(val):
    return val is not None

In [22]:
exists(None)

True

In [33]:
rotations = repeat(torch.eye(3), '... -> b n ...', b = 1, n = 256)  # (batch x seq x rot1 x rot2) - example is identity
rotations

tensor([[[[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         ...,

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]],

         [[1., 0., 0.],
          [0., 1., 0.],
          [0., 0., 1.]]]])